name: Release Main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml
    with:
      environment: "release"
  release:
    needs: build_and_test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run create release script
        run: ./scripts/ci/create_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash