name: Release Dev

on:
  push: 
    branches: 
      - dev

jobs:
  build_and_test:
    uses: .github/workflows/build_and_test.yml
    with:
      environment: "debug"
  build:
    needs: build_and_test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check if "dev" tag exists
        id: check_tag
        run: |
          if git rev-parse dev >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Remove Existing "dev" Tag / Release
        if: env.exists == 'true'
        run: |
          gh release delete dev
          git tag -d dev
          git push origin --delete dev

      - name: Create New "dev" Tag
        run: |
          git tag dev
          git push origin dev

      - name: Create Release
        run: |
          gh release create dev --title "Development Release" --prerelease <<< ""
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash