name: Release Dev

on:
  push: 
    branches: 
      - dev

jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml
    with:
      environment: "debug"
  pre-release:
    needs: build_and_test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run create pre-release script
        run: ./scripts/ci/create_pre_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash